SET ThousandSep=',';
SET DecimalSep='.';

Let MyMessage = NoOfRows('MainTable') & ' rows in Main Table';
Trace $(MyMessage);
Trace My
    other
message
;

///$tab Main


// Resident load with conditions

rem Test rem comment;

/*
Multi
    Line
        Comment
            Example

*/

[My table]:
LOAD
    MyField   as [My Field],
    Name,
    sum(Area) as AggrField
RESIDENT 
    MyTable
Where 
        1 = 1
    and 2 = 2
;

Drop table [My table];